### ISSUE TITLE
More sources

### ISSUE THREAD

**Issue by cesalmo** [iwannabelikemike/plugin.video.sparkle#12]
Please, add https://www.reddit.com/r/SoccerStreaming/

thank you

**Comment by prydda** [comment]
Actually, they closed the subreddit. 

@iwannabelikemike can you please add: [https://www.reddit.com/r/redditsoccer/](url)

**Comment by prydda** [comment]
@iwannabelikemike most streamers moved to https://www.footybite.com/football/ 
possible to search for acestream there aswell?

**Comment by whiplash78** [comment]
Is there a chance to add a feature that allows to add a reddit ?

**Comment by abdhan** [comment]
Like @whiplash78 said, if you can enter a subreddit name that would be great.
