### ISSUE TITLE
Seems the subreddit has moved again

### ISSUE THREAD

**Issue by ganjam0n** [iwannabelikemike/plugin.video.sparkle#14]
the soccerstreams has moved to /redsoccer/ for now, do not know how long that will last though, im worried speculation is, is that everything will move to a different site at some point if this keeps up which is going to mess everything up for all the people launching acestreams from theyre android boxs :( .

**Comment by abdhan** [comment]
Currently it's /r/soccerstreams69 run by the same mods. Ability to parse links from webpages will be great since that is the best alternative to Reddit and Discord.

**Comment by L2501** [comment]
/r/soccerstreams69 is banned

**Comment by chinedu40** [comment]
/r/footballconnection is the new subreddit

**Comment by ganjam0n** [comment]
i think the boxing streams subreddit is scared to drop streams too now, i think reddit is done, what a shame, sparkle was such a great reddit scraper, i hope the dev moves to wherever the people decide to move to and makes a scraper for that, if not thanks for this plugin and the hard work. <3

**Comment by rafuse** [comment]
New site according to /r/soccerstreams admins is footybite.com. I'm not a dev, but maybe a rewrite of the code is possible to point to this url?
